version: '3.8'

services:
  profiles:
    build:
      context: profiles
      dockerfile: Dockerfile
    environment:
      - PRODUCTION=false
    volumes:
      - ./profiles/src:/usr/src/app/src

  users:
    build:
      context: users
      dockerfile: Dockerfile
    environment:
      - PRODUCTION=false
    volumes:
      - ./users/src:/usr/src/app/src
      
  products:
    build:
      context: products
      dockerfile: Dockerfile
    environment:
      - PRODUCTION=false
    volumes:
      - ./products/src:/usr/src/app/src

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - profiles
      - users
      - products
