version: '3.3'

services:
  profiles:
    build:
      context: profiles
      dockerfile: Dockerfile
    environment:
      - PRODUCTION=false
    volumes:
      - ./profiles/src:/usr/src/app/src

  users:
    build:
      context: users
      dockerfile: Dockerfile
    environment:
      - PRODUCTION=false
    volumes:
      - ./users/src:/usr/src/app/src

  transactions:
    build:
      context: transactions
      dockerfile: Dockerfile
    environment:
      - PRODUCTION=false
    volumes:
      - ./transactions/src:/usr/src/app/src

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - profiles
      - users
      - transactions

  mongo:
    image: mongo
    restart: always
    container_name: mongo-test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo/data:/data/db